services:
  # =========================
  # FALCO IDS
  # =========================
  falco:
    image: falcosecurity/falco:0.43.0
    container_name: falco-agent
    hostname: falco-host
    privileged: true
    restart: unless-stopped

    volumes:
      - ./falco-agent/config/falco.yaml:/etc/falco/falco.yaml:ro
      - ./falco-agent/config/rules:/etc/falco/rules:ro
      - ./falco-agent/falco-plugins:/usr/lib/falco/plugins:ro
      - /var/run/docker.sock:/host/var/run/docker.sock:ro
      - /dev:/host/dev:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /sys/kernel/tracing:/sys/kernel/tracing:ro

    environment:
      - HOST_ROOT=/host
      - FALCOCTL_DRIVER_TYPE=modern_ebpf
      - FALCO_LOG_LEVEL=debug

    networks:
      - prod-healio

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # =========================
  # GRAFANA ALLOY (COLLECTOR)
  # =========================
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: ${HOSTNAME:-collector-01}
    restart: unless-stopped

    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

    volumes:
      - ./alloy/config/config.alloy:/etc/alloy/config.alloy:ro
      - ./alloy/certs:/etc/alloy/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy-data:/var/lib/alloy/data
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro

    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ROOT=/host/root

      - PROMETHEUS_URL=http://192.168.55.193:9090/       # Prometheus remote write
      - LOKI_URL=http://192.168.55.193:3100/loki/api/v1/push  # Loki log ingestion

    pid: host
    privileged: true

    networks:
      - prod-healio

volumes:
  alloy-data:

networks:
  prod-healio:
    name: prod-healio
    driver: bridge
