server {
    listen 443 ssl;
    listen 443 quic reuseport;
    
    http3 on;
    
    server_name falco.local;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        # SECURITY RESTRICTION: Localhost only
        # Remove these 2 lines only if you have VPN/auth in front
        allow 127.0.0.1;
        deny all;
        
        proxy_pass http://falco:8765;
        proxy_http_version 1.1;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
